Library/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Library.Data.Interface;
using Library.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers
{
    [Authorize]
    public class AuthorController : Controller
    {
        #region Contructor + Repository

        private readonly IAuthorRepository repo;

        public AuthorController(IAuthorRepository author)
        {
            repo = author;
        }
        #endregion

        #region List.............................
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var x = await repo.GetAllAuthors();
            return View(x);
        }
        #endregion

        #region Add..............................

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(Author author)
        {
            if (ModelState.IsValid)
            {
                repo.Add(author);
                await repo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }
        #endregion

        #region Edit.............................
        public async Task<IActionResult> Edit(int ID)
        {
            var c = await repo.GetAuthorByID(ID);
            return View(c);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Author author)
        {
            if (ModelState.IsValid)
            {
                repo.Update(author);
                await repo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }
        #endregion

        #region Delete...........................
        public async Task<IActionResult> Delete(int ID)
        {
            var c = await repo.GetAuthorByID(ID);
            return View(c);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirm(int ID)
        {
            if (ModelState.IsValid)
            {
                var c = await repo.GetAuthorByID(ID);
                repo.Delete(c);
                await repo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        #endregion

        #region Details...........................
        public async Task<IActionResult> Detail(int ID)
        {
            var c = await repo.GetAuthorByID(ID);
            return View(c);
        }
        #endregion
    }
}

Library/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Library.Data.Interface;
using Library.Data.Models;
using Library.Data.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers
{
    [Authorize]
    public class BookController : Controller
    {
        #region Constructor + Repository

        private readonly IBookRepository repo;
        private readonly IAuthorRepository repoAuthor;
        public BookController(IBookRepository book, IAuthorRepository authorRepository)
        {
            repo = book;
            repoAuthor = authorRepository;
        }
        #endregion

        #region List.............................
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var x = await repo.GetBookWithAuthors();
            return View(x);
        }
        #endregion

        #region Add..............................

        public async Task<IActionResult> Add()
        {
            var BookVM = new BookViewModel
            {
                authors = await repoAuthor.GetAllAuthors()
            };
            return View(BookVM);
        }

        [HttpPost]
        public async Task<IActionResult> Add(BookViewModel bookViewModel)
        {
            if (ModelState.IsValid)
            {
                repo.Add(bookViewModel.book);
                await repo.Save();
                return RedirectToAction(nameof(Index));
            }
            bookViewModel.authors = await repoAuthor.GetAllAuthors();
            return View(bookViewModel);
        }
        #endregion

        #region Edit.............................
        public async Task<IActionResult> Edit(int ID)
        {
            var BookVM = new BookViewModel
            {
                book = await repo.GetBookByID(ID),
                authors = await repoAuthor.GetAllAuthors()
            };
            return View(BookVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Book book)
        {
            if (ModelState.IsValid)
            {
                repo.Update(book);
                await repo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        #endregion

        #region Delete...........................
        public async Task<IActionResult> Delete(int ID)
        {
            var c = await repo.GetBookByID(ID);
            return View(c);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirm(int ID)
        {
            if (ModelState.IsValid)
            {
                var c = await repo.GetBookByID(ID);
                repo.Delete(c);
                await repo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        #endregion

        //#region Details...........................
        //public async Task<IActionResult> Detail(int ID)
        //{
        //    var c = await repo.GetBookByID(ID);
        //    return View(c);
        //}
        //#endregion
    }
}

Library/Controllers/LendController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Library.Data.Interface;
using Library.Data.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers
{
    [Authorize]
    public class LendController : Controller
    {
        private readonly ICustomerRepository repoCust;
        private readonly IBookRepository repoBook;

        public LendController(IBookRepository bookRepository, ICustomerRepository customerRepository)
        {
            repoCust = customerRepository;
            repoBook = bookRepository;
        }

        #region List Available Books
        public IActionResult Index()
        {
            var AvailableBooks = repoBook.GetAvailableBook();
            return View(AvailableBooks);
        }
        #endregion

        #region Lend.............................
        public async Task<IActionResult> Lend(int ID)
        {
            var avabook = new LendBookViewModel
            {
                book = await repoBook.GetBookByID(ID),
                customers = await repoCust.GetAllCustomer()
            };
            return View(avabook);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Lend(LendBookViewModel lendBookViewModel)
        {
            var book = await repoBook.GetBookByID(lendBookViewModel.book.ID);
            var customer = await repoCust.GetCustomerByID((int)lendBookViewModel.book.CustomerID);
            //book.CustID = customer.ID;
            book.Customer = customer;

            repoBook.Update(book);
            await repoBook.Save();
            return RedirectToAction(nameof(Index));
        }

        #endregion

    }
}

Library/Controllers/ReturnController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Library.Data.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers
{
    [Authorize]
    public class ReturnController : Controller
    {
        private readonly ICustomerRepository repoCust;
        private readonly IBookRepository repoBook;

        public ReturnController(IBookRepository bookRepository, ICustomerRepository customerRepository)
        {
            repoCust = customerRepository;
            repoBook = bookRepository;
        }
        #region Return List......................
        public IActionResult Index()
        {
            var LendedBook = repoBook.GetBookWithAuthorAndCustomer();
            if (LendedBook == null || LendedBook.Count() == 0)
            {
                return View("Empty");
            }
            return View(LendedBook);
        }
        #endregion

        #region Return Book......................
        public async Task<IActionResult> Return(int ID)
        {
            var book = await repoBook.GetBookByID(ID);
            book.Customer = null;
            book.CustomerID = null;
            repoBook.Update(book);
            await repoBook.Save();

            return RedirectToAction(nameof(Index));
        }
        #endregion
    }
}

Library/Views/Shared/_Layout.cshtml
@inject SignInManager<IdentityUser> signManager;
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/PaperBootstrap/PaperBootstrap.css" rel="stylesheet" />
    @*<link href="~/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />*@
    @*<link href="~/twitter-bootstrap/css/bootstrap-grid.css" rel="stylesheet" />*@
</head>
<body>
    <div>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" asp-controller="Home" asp-action="Index">Library Management System</a>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        @*<li class="active"><a href="https://bootswatch.com/3/paper/#">Link <span class="sr-only">(current)</span></a></li>*@
                        <li><a asp-controller="Customer" asp-action="Index">Customer</a></li>
                        <li><a asp-controller="Author" asp-action="Index">Author</a></li>
                        <li><a asp-controller="Book" asp-action="Index">Book</a></li>
                        <li><a asp-controller="Lend" asp-action="Index">Lend</a></li>
                        <li><a asp-controller="Return" asp-action="Index">Return</a></li>

                        @*<li class="dropdown">
                                <a href="https://bootswatch.com/3/paper/#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="https://bootswatch.com/3/paper/#">Action</a></li>
                                    <li><a href="https://bootswatch.com/3/paper/#">Another action</a></li>
                                    <li><a href="https://bootswatch.com/3/paper/#">Something else here</a></li>
                                    <li class="divider"></li>
                                    <li><a href="https://bootswatch.com/3/paper/#">Separated link</a></li>
                                    <li class="divider"></li>
                                    <li><a href="https://bootswatch.com/3/paper/#">One more separated link</a></li>
                                </ul>
                            </li>*@
                    </ul>
                    <form class="navbar-form navbar-left" role="search">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Search">
                        </div>
                        <button type="submit" class="btn btn-default">Submit</button>
                    </form>
                    <ul class="nav navbar-nav navbar-right">

                        @if (signManager.IsSignedIn(User))
                        {
                            <li>
                                <a asp-action="Logout" asp-controller="Account">Welcome ! @User.Identity.Name - Logout</a>
                                @*<form method="post" asp-action="logout" asp-controller="account">
                                        <button type="submit" class="btn btn-danger">Logout : @User.Identity.Name</button>
                                    </form>*@
                            </li>
                        }
                        else
                        {
                            <li><a asp-controller="Account" asp-action="Login">Login</a></li>
                            <li><a asp-controller="Account" asp-action="Register">Registration</a></li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            @RenderBody()
        </div>

    </div>
</body>
</html>